# Dependabot configuration for automated dependency updates
version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "openspp/security-team"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      # Group all minor and patch updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Don't update Odoo since it's vendored
      - dependency-name: "odoo"
      # Lock specific versions that are known to work
      - dependency-name: "python-jose"
        versions: [">3.3.0"]
      - dependency-name: "extendable-pydantic"
        versions: ["\!=1.3.0"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "openspp/devops-team"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/setup/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "openspp/devops-team"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"
EOF < /dev/null