# GitHub Release Configuration

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - github-actions
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 📦 Packaging
      labels:
        - packaging
        - build
    - title: 🔧 Maintenance
      labels:
        - maintenance
        - chore
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔒 Security
      labels:
        - security
    - title: ⬆️ Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"